title: Proxima Theme
description: Proxima is a theme for GitHub Pages, with GitHub-like styling
remote_theme: dannyben/jekyll-theme-proxima
google_analytics:

plugins:
- jekyll-seo-tag

github:
  is_project_page: true
  repository_url: http://github.com/dannyben/jekyll-theme-proxima
  owner_url: http://github.com/dannyben
  owner_name: DannyBen
  repository_name: jekyll-theme-proxima

# header:
#   background: '#fda'
#   color: black

# footer:
#   border: '10px solid red'

