title: Proxima theme
description: Proxima is a theme for GitHub Pages, with GitHub-like styling
theme: jekyll-theme-proxima
google_analytics:

# header:
#   background: '#789'
#   color: white

# footer:
#   background: '#eee'